name: holochat-crawler
services:
  holochat-crawler:
    public: true
    image: okteto/holochat-crawler:stacks
    build: .
    replicas: 1
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
    volumes:
      - /backup
    environment:
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - DISCORD_WEBHOOK_ID=$DISCORD_WEBHOOK_ID
      - DISCORD_WEBHOOK_TOKEN=$DISCORD_WEBHOOK_TOKEN
      - OPEN_EXCHANGE_RATES_APP_ID=$OPEN_EXCHANGE_RATES_APP_ID
